### ISSUE TITLE
unbounded loop could default to infinity if capture has sensitivity >1 in the body

### ISSUE THREAD

**Issue by ooovi** [DiffMu/DiffPrivacyInferenceHs#126]
right now sensitivity loops with variable number of iterations are only allowedif the capture has sensitivity 1 in the body, which is ensured by a corrensponding constraint. when loop is used incorrectly (that is capture sensitivity is >1) the constraint fails and typecheker errors. instead we could in this case just scale all contexts with infinity.

**Comment by MxmUrw** [comment]
We do **NOT** want this to happen automatically. We do want a good error message instead.
