### ISSUE TITLE
Bug in scoping

### ISSUE THREAD

**Issue by MxmUrw** [DiffMu/DiffPrivacyInferenceHs#138]
The following example:
```julia
function test7()
  c = 0
  function apply(f)
    x -> f(x)
  end
  c = 1
  g = apply(x -> x + c)
  c = 4
  g(1)
end

julia> test7()
5
```
is checked by us with:
```
Type:
{
  --------------------------
   -> Int[2.0]

}
```

**Comment by MxmUrw** [comment]
The direct cause of this issue is the change from eb1993d. But this was done for #58, which is still valid.

The problem is that when functions are passed as arguments to other functions it is unclear when to use which scope.

Another example is:
```julia
function test9()
  function f1()
    x1 = a
    function f2()
      x2 = a
      function f3()
        x3 = a
        function f4()
          x1 * x2 * x3
        end
      end
    end
  end
  a = 2
  r1 = f1()
  a = 3
  r2 = r1()
  a = 4
  r3 = r2()
  a = 5
  r4 = r3()
  r4
end
```

**Comment by MxmUrw** [comment]
Something which might be related is the following:
```julia
function test9()
  a = 0
  function f1()
    x1 = a
    function f2()
      x2 = a
      function f3()
        x3 = a
        function f4()
          x1 * x2 * x3
        end
      end
    end
  end
  a = 2
  r1 = f1()
  a = 3
  r2 = r1()
  a = 4
  r3 = r2()
  a = 5
  r4 = r3()
  r4
end
test9 (generic function with 1 method)

julia> test9()
24
```
For which we get
```
Encountered error: Variable not in scope: Just x1
()
```
Even *with* the fix for #58.

**Comment by MxmUrw** [comment]
This is another bug in a series of attempts to get scoping right: #18, #20, #22.

**Comment by MxmUrw** [comment]
For now, we want to mitigate all scoping problems by disallowing variables to be assigned values of different types. This way, if a variable is in scope at some point during type checking, its type is necessarily the correct one.

**Comment by ooovi** [comment]
This is not satisfactory in the long run, as stuff like this is forbidden:
```
a = 1
foo(a)
a = 2
bar(a)
```
because `a` gets two different const types that cannot be unified, even though they have the same type in julia. or:
```
M = M + N
```
will fail if N is a matrix with another norm than M, even though matrix norms are not even transparent in julia.
that's going to be hard to communicate...it would be better to do something like supremum there.
also, the whole delayed-scopes-dance is not necessary anymore if we do this. 
this is probably related to #116

**Comment by ooovi** [comment]
we just entirely forbid reassignment of variables, as it's not strictly necessary and a lot of pain!
