### ISSUE TITLE
think about doing scopes

### ISSUE THREAD

**Issue by ooovi** [DiffMu/DiffPrivacyInferenceHs#141]
we restricted reassignment of variables because it is a lot of pain and not super useful. onc we have some free time (hah) we could consider doing something about it. see this beautiful list of issues:
#18 
#19
#20 
#22 
#138 
there are some tests in `test/Spec/BrokenScoping.hs` te be considered.

**Comment by MxmUrw** [comment]
We now have relatively strict rules about when reassignment of variables is allowed. (Only when the variable is used in a single scope.) This is fully implemented. See #140.
