### ISSUE TITLE
Allow inference of colors, such that binds need not be annotated

### ISSUE THREAD

**Issue by MxmUrw** [DiffMu/DiffPrivacyInferenceHs#154]
This involves the following:
 - Instead of `check_sens` and `check_priv` there are `infer` and `check`, which both return a color, and `check` also gets a color as input.
 - It is not allowed to have mixed choices where some are privacy and some are sensitivity. Also, arguments which are functions need to be annotated with `PrivacyFunction` (or similar), because when we infer the color for `f a` where f is an argument, we need to know from somewhere what `f` is.
 - There is no longer a distinction between `bind` and `let`, this is inferred.

This is a solution for #98.

**Comment by ooovi** [comment]
instead i will write a preprocessing step / serperate typechecker that infers the colors of terms and makes binds into binds.

**Comment by ooovi** [comment]
done in https://github.com/DiffMu/DiffPrivacyInferenceHs/commit/41dceb96f224160f8b62dd9019fefe6778e6ab71
