### ISSUE TITLE
Compute the sensitivity of index terms, zero grad

### ISSUE THREAD

**Issue by MxmUrw** [DiffMu/DiffPrivacyInferenceHs#164]
- We have terms to access the contents of a matrix/vector (`Index m i j` and `VIndex v i`) which do not appear as such in duet. The question is what scaling should be applied to the context of the index.

 - Is ZeroGrad 1 sensitive in the model?

**Comment by ooovi** [comment]
![mindex](https://user-images.githubusercontent.com/79147175/153457105-b0a36d42-df6d-4b20-b97e-7ee95aab0cc4.png)

actually `Index` appears in duet, but it is hidden on page 21 of the paper. it is 1-sensitive in the matrix and infinitely sensitive in the indices. it's the same for vectors.

`ZeroGrad` is (at least in our way of treating gradients as if they were totally independant from their models) only an `mcreate` term used on the model dimension. it is hence 0-sensitive in the model. in addition, the clipping parameter does not need to be unbounded in the result matrix, as we know it only has zeros.
