### ISSUE TITLE
Fix behaviour of if-else-branches

### ISSUE THREAD

**Issue by MxmUrw** [DiffMu/DiffPrivacyInferenceHs#17]
In julia it is possible to do:
```julia
julia> function f(x)
       if x == 3
          return 5.0
       else
          return 4
       end
       end
f (generic function with 1 method)

julia> f(1)
4

julia> f(3)
5.0
```
This means that the type of ```f(a)``` in julia would be something like ```Union{Integer,Real}``` which we currently cannot express.
But which we should, since further dispatching on the return value depends on knowning when which of those types is going to be the actual one.

The solution to require all branches to have the same type does not work naively, since then we would forbid to return ```Int[1]``` and ```Int[2]``` in different branches.

- [ ] Real question: How do we deal with this?
- [ ] Offtopic question: Do we need a DMBool type?

**Comment by MxmUrw** [comment]
Question: Do we need a DMBool type?

**Comment by MxmUrw** [comment]
We currently get the following result for the given ```f```:
```
Result: (Fun([([Num(τ_18[--]) @ ∞] -> Num(Real[--])) @ Just ["Any"]]),
State:
- watcher: IsChanged

Meta:
- sens vars: []
- type vars: [τ_18 : BaseNum, τ_5 : *]
- sens subs:   η_1 := 0, s_3 := 4.0, η_0 := 1, s_2 := 5.0
- type subs:   τ_17 := Real, τ_11 := Real[--], τa_1 := Int[3.0], τr_2 := Int[--], τ_8 := Num(Int[4.0]), τ_16 := Int, τ_9 := Num(Real[--]), τ_10 := Real[5.0], τa_0 := τ_18[--], τ_15 := Int, τ_3 := Num(τ_18[--]), τ_6 := Num(Real[5.0]), τ_14 := Real, τ_7 := Num(Real[--]), τ_13 := Real[--], τ_4 := Num(Real[--]), τ_12 := Int[4.0]
- fixed TVars: []
- constraints:
   - top:

   - others:
```

**Comment by ooovi** [comment]
we will put an IsJuliaEqual constraint on the branch types. if we want to be able to resolve dispatch, that's all we can do

**Comment by ooovi** [comment]
fixed in this [https://github.com/DiffMu/DiffPrivacyInferenceHs/commit/0292879973c34e85e4e8c88ffee833a094a2841d](commit)
