### ISSUE TITLE
Decide on formatting for DMTypes

### ISSUE THREAD

**Issue by MxmUrw** [DiffMu/DiffPrivacyInferenceHs#236]
For example how to print Matrix / Vector types.

For example #65 is relevant here: how much do we print for the use.

**Comment by ooovi** [comment]
we opted for an "extension of the julia types" formatting, which was done in https://github.com/DiffMu/DiffPrivacyInferenceHs/commit/ba0fab27d0eeedf38d2f5ba9b95999571ed9b9c2
