### ISSUE TITLE
do we need unique arg names?

### ISSUE THREAD

**Issue by ooovi** [DiffMu/DiffPrivacyInferenceHs#27]
maybe it is necessary for Arg terms to have unique names. we should try to break it.

To be clear, this issue is about the following case:
```julia
function test(a,b)
  function f(a)
    a
  end
end
```

Do we do the correct thing here?

**Comment by MxmUrw** [comment]
We implement unique arg names in #45. But this still leaves the question where exactly in the typechecker we need them. See TODOs in the code.
