### ISSUE TITLE
do we need more powerful symbolic computation, or SAT solving?

### ISSUE THREAD

**Issue by ooovi** [DiffMu/DiffPrivacyInferenceHs#35]
as of now, we only do very basic simplification of arithmetic terms in sensitivity and privacy annotations (see the [function `tryComputeSym`](https://github.com/DiffMu/DiffPrivacyInferenceHs/blob/7bf4e93158ce62d33a5331dd2db3e40b0c75d454/src/DiffMu/Core/Symbolic.hs#L88-L142)). we probably need more sophisticated equation solving, taking into account stuff like associativity laws and special behaviour of our `exp, ln, sqrt` etc friends. also we might need to check if the terms are even well-defined given all remaining constraints on the variables, so we can error upon `ln(s)` given `isLessEqual(s,0)` (this is a very contrived example and might not even be a possible situation)?

**Comment by MxmUrw** [comment]
Since things have worked fine for now, this is not something we are going to do.
