### ISSUE TITLE
Typecheck the MNIST example

### ISSUE THREAD

**Issue by ooovi** [DiffMu/DiffPrivacyInferenceHs#49]
the example lives on the julia branch in https://github.com/DiffMu/DiffPrivacyInference.jl/tree/main/test/flux_dp
i will also manually prove a privacy bound and see what diffmu has to say about that

**Comment by ooovi** [comment]
i manually inferred that the privacy of the first two parameters is
```(4.0⋅eps⋅sqrt(2.0⋅(0.0 - ln(eta))⋅d)⋅sqrt(2.0⋅(0.0 - ln(mu))⋅n), mu + n⋅eta + del⋅n⋅d)```
for some `eps, del` in `(0,1)` and some `eta, mu` in `(0,1]` which is exactly what delmu gives us! 🥳

**Comment by MxmUrw** [comment]
Ok, that is very nice!

**Comment by ooovi** [comment]
we do, docs here: https://github.com/DiffMu/DiffPrivacyInference.jl/tree/main/test/flux_dp
