### ISSUE TITLE
Way to mark function as "black box"

### ISSUE THREAD

**Issue by MxmUrw** [DiffMu/DiffPrivacyInferenceHs#69]
on the julia side, we annotate with `:: BlackBox` or something. we introduce an extra DMTerm that has the same shape as `FLet` and behaves similarly (adding choice etc) but just sets sensitivities/privacies of all arguments to infinity.

**Comment by ooovi** [comment]
it is not safe to assume that a black-boxed function does not mutate stuff in the current scope. we should think of a way to prevent that, maybe have them be in a seperate namespace or using one of these:
https://github.com/JuliaLang/julia/pull/41777
https://github.com/tkf/Mutabilities.jl

**Comment by MxmUrw** [comment]
For example:
```julia
function bb(a,x) :: BlackBox
  a + x + g_1 + g_2
end
g_1 = 1
g_2 = 2
function f(a)
  # We know that this is a black box
  # If `f` is called from below, then `g_1`
  # and `g_2` are in the "global scope"
  res = bb(a,a)
  term(res,...)
end
f(3)
```
Here, in the call `f(3)` the black box `bb` has the virtual type
`bb :: (A,X),[G_1, G_2] -> Y` if we do not consider mutation,
or the type `bb :: (A,X),[G_1, G_2] -> (Y,[G_1,G_2])` if we do.


By the black box analysis, this term is changed to the following:
```julia
function bb(a,x) :: BlackBox
  a + x + g_1 + g_2
end
g_1 = 1
g_2 = 2
function f(a)
  # without mutation
  res = BlackBoxApply(bb(a,a),[g_1,g_2])
  term(res,...)

  # with mutation
  (res,[g_1,g_2]) = BlackBoxApplyMut(bb(a,a),[g_1,g_2])
  term(res,...)
end
f(3)
```
