### ISSUE TITLE
handle recursion

### ISSUE THREAD

**Issue by ooovi** [DiffMu/DiffPrivacyInferenceHs#73]
recursion is very forbidden. the julia-side expression sanitizer catches direct recursion, i.e. functions calling themselves directly. more complicated cases are not yet handled, like
```
f(x) = g(1)
g(x) = f(100)
```

**Comment by MxmUrw** [comment]
Because of our demutation parsing we require that variables are defined before they can be used. Thus code has to be properly ordered, and the above example is now forbidden.

This does not mean that the problem is solved, the following example still gives an infinite loop:
```
julia> typecheck_hs_from_string("
           g = 0
           f(x) = g(100)
           g(x) = f(1)
           ")
```

**Comment by MxmUrw** [comment]
Since this issue was written we switched away from our delayed typechecking monad.

See [d7a2b3d](https://github.com/DiffMu/DiffPrivacyInferenceHs/commit/d7a2b3db67580a66880644886d61a5afed2eb6a0), #138, #140.

**Comment by MxmUrw** [comment]
The case list above seems exhaustive. Tests added.
