### ISSUE TITLE
get type annotations straight

### ISSUE THREAD

**Issue by ooovi** [DiffMu/DiffPrivacyInferenceHs#75]
either find a way to support annotations like
```
x :: Int = 3
```
or remove type annotations from variables/singletons altogether. they are annoying.

also, function return type annotations are not yet possible

**EDIT**: Decision: We do the following:
- [x] #243
- [x] #244

**Comment by MxmUrw** [comment]
When rewriting demutation #190, we do not pass the input annotations further. If we decide to actually implement them, this has to be done.
