### ISSUE TITLE
in-place/lazy matrix operations are problematic

### ISSUE THREAD

**Issue by ooovi** [DiffMu/DiffPrivacyInferenceHs#78]
from the docs of transpose:
  Lazy transpose. Mutating the returned object should appropriately mutate A. Often, but not always, yields Transpose(A), where Transpose is a lazy transpose wrapper. Note that this
  operation is recursive.

**Comment by MxmUrw** [comment]
We currently do not allow for mutating functions on matrices, see #199.

**Comment by ooovi** [comment]
we just don't implement any mutating matrix functions at the moment. demutation expects this, so it's important to think properly be
